export const NIGERIAN_BANKS_SEED = [
  // --- Commercial Banks ---
  { name: 'Access Bank', code: '044' },
  { name: 'Access Bank (Diamond)', code: '063' },
  { name: 'Citibank Nigeria', code: '023' },
  { name: 'Ecobank Nigeria', code: '050' },
  { name: 'Fidelity Bank', code: '070' },
  { name: 'First Bank of Nigeria', code: '011' },
  { name: 'First City Monument Bank', code: '214' },
  { name: 'Globus Bank', code: '00103' },
  { name: 'Guaranty Trust Bank', code: '058' },
  { name: 'Heritage Bank', code: '030' },
  { name: 'Keystone Bank', code: '082' },
  { name: 'Optimus Bank', code: '000036' },
  { name: 'Parallex Bank', code: '104' },
  { name: 'Polaris Bank', code: '076' },
  { name: 'PremiumTrust Bank', code: '105' },
  { name: 'Providus Bank', code: '101' },
  { name: 'Signature Bank', code: '000034' },
  { name: 'Stanbic IBTC Bank', code: '039' },
  { name: 'Standard Chartered Bank', code: '022' },
  { name: 'Sterling Bank', code: '232' },
  { name: 'Suntrust Bank', code: '100' },
  { name: 'Union Bank of Nigeria', code: '032' },
  { name: 'United Bank For Africa (UBA)', code: '033' },
  { name: 'Unity Bank', code: '215' },
  { name: 'Wema Bank', code: '035' },
  { name: 'Zenith Bank', code: '057' },

  // --- Digital Banks & FinTechs ---
  { name: 'ALAT by WEMA', code: '035A' },
  { name: 'Carbon', code: '565' },
  { name: 'Dot Microfinance Bank', code: '50162' },
  { name: 'Eyowo', code: '50126' },
  { name: 'Fairmoney Microfinance Bank', code: '51318' },
  { name: 'GoMoney', code: '100022' },
  { name: 'Kuda Bank', code: '50211' },
  { name: 'Moniepoint MFB', code: '50515' },
  { name: 'OPay (PayCom)', code: '999992' },
  { name: 'Paga', code: '100002' },
  { name: 'PalmPay', code: '999991' },
  { name: 'Rubies MFB', code: '125' },
  { name: 'Safe Haven MFB', code: '51113' },
  { name: 'Sparkle Microfinance Bank', code: '51310' },
  { name: 'Tangerine Money', code: '51269' },
  { name: 'VFD Microfinance Bank Limited', code: '566' },

  // --- Payment Service Banks (PSBs) ---
  { name: '9mobile 9Payment Service Bank', code: '120001' },
  { name: 'Airtel Smartcash PSB', code: '120004' },
  { name: 'HopePSB', code: '120002' },
  { name: 'MTN Momo PSB', code: '120003' },

  // --- Non-Interest & Merchant Banks ---
  { name: 'Coronation Merchant Bank', code: '559' },
  { name: 'FSDH Merchant Bank Limited', code: '501' },
  { name: 'Jaiz Bank', code: '301' },
  { name: 'Lotus Bank', code: '303' },
  { name: 'Rand Merchant Bank', code: '502' },
  { name: 'TAJ Bank', code: '302' },

  // --- Major Microfinance & Mortgage Banks ---
  { name: 'Abbey Mortgage Bank', code: '801' },
  { name: 'ASO Savings and Loans', code: '401' },
  { name: 'Bowen Microfinance Bank', code: '50931' },
  { name: 'CEMCS Microfinance Bank', code: '50823' },
  { name: 'Ibile Microfinance Bank', code: '51244' },
  { name: 'Links MFB', code: '50549' },
  { name: 'Mint MFB', code: '50304' }
];