import { Prop } from '@nestjs/mongoose';
import { Schema } from 'mongoose';

export class BaseEntity {
  // _id auto-generated by MongoDB
  // createdAt & updatedAt handled by Mongoose timestamps: true

  @Prop({ unique: true })
  serialNumber: number;

  @Prop({ default: false })
  isDeleted: boolean;

  @Prop()
  deletedAt: Date;

  @Prop({ type: Schema.Types.ObjectId })
  deletedBy: Schema.Types.ObjectId;
}
